[pkg.arrl160]
tag = "ARRL 160m contest"
msg = "ARRLの160mコンテストです."
web = "https://github.com/jr8ppg/zLog_cfgdat"
doc = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/arrl160/README.md"
use = ["dat.arrlsec", "cfg.arrl160dx"]
exp = "stable"

[cfg.arrl160dx]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/arrl160/arrl160dx.cfg"

[dat.arrlsec]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/arrl160/arrlsec.dat"

[pkg.ja8_50th]
tag = "ALL JA8 contest(50th anniversary)"
msg = "ALL JA8コンテスト2023(50周年)です。"
web = "https://github.com/jr8ppg/zLog_cfgdat"
doc = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ja8_50th/README.md"
use = ["dat.ja8_50th", "cfg.ja8_50th"]
exp = "stable"

[cfg.ja8_50th]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ja8_50th/JA8_50th.CFG"

[dat.ja8_50th]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ja8_50th/JA8_50th.DAT"

[pkg.KSContest]
tag = "上川宗谷支部コンテスト"
msg = "上川宗谷支部コンテストです。"
web = "https://github.com/jr8ppg/zLog_cfgdat"
doc = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/KSContest/README.md"
use = ["dat.KSContest", "cfg.KSContest"]
exp = "stable"

[cfg.KSContest]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/KSContest/KSContest.cfg"

[dat.KSContest]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/KSContest/KSContest.dat"

[pkg.ISB]
tag = "石狩後志支部コンテスト"
msg = "石狩後志支部コンテスト（管内用／管外用）です。"
web = "https://github.com/jr8ppg/zLog_cfgdat"
doc = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ISB/README.md"
use = ["dat.ISBnew", "cfg.ISBnew_i", "cfg.ISBnew_o"]
exp = "stable"

[cfg.ISBnew_i]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ISB/ISBnew_i.cfg"

[cfg.ISBnew_o]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ISB/ISBnew_o.cfg"

[dat.ISBnew]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ISB/ISBnew.dat"

