[pkg.arrl160]
tag = "ARRL 160m contest"
msg = "ARRLの160mコンテストです."
web = "https://github.com/jr8ppg/zLog_cfgdat"
doc = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/arrl160/README.md"
use = ["dat.arrlsec", "cfg.arrl160dx"]
exp = "stable"

[cfg.arrl160dx]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/arrl160/arrl160dx.cfg"

[dat.arrlsec]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/arrl160/arrlsec.dat"

[pkg.ja8_50th]
tag = "ALL JA8 contest(50th anniversary)"
msg = "ALL JA8コンテスト2023(50周年)です。"
web = "https://github.com/jr8ppg/zLog_cfgdat"
doc = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ja8_50th/README.md"
use = ["dat.ja8_50th", "cfg.ja8_50th"]
exp = "stable"

[cfg.ja8_50th]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ja8_50th/JA8_50th.CFG"

[dat.ja8_50th]
url = "https://raw.githubusercontent.com/jr8ppg/zLog_cfgdat/main/plugins/rules/ja8_50th/JA8_50th.DAT"

